### PR TITLE
Fix simulated measurements domain - closes #337

### LINKED ISSUE #337: Simulated measurements should be shown for the width of the flux plot, not just during the eclipse.
Simulated measurements should be shown for the width of the flux plot, not just during the eclipse.

### PR DESCRIPTION
**Pull request by nikolas**
2019-06-06-133107_548x459_scrot

### CODE REVIEW

File: exoplanet-transit-simulator/src/LightcurveView.jsx [hunk 1]
```diff
@@ -20,40 +20,35 @@ export default class LightcurveView extends React.Component {
...
 
-        // Find simMeasurementNumber random samples out of lightcurve
-        // data. These will be the points where noise is generated.
-        const randomizedData = shuffleArray(lightcurveData);
-        // Get the first simMeasurementNumber samples out of the
-        // randomized data.
-        const samples = randomizedData.slice(
-            0, this.props.simMeasurementNumber);
+        const xExtent = d3.extent(lightcurveData, d => d[0]);
+        console.log('xExtent', xExtent);
```
Comment (sdreher) [inline exoplanet-transit-simulator/src/LightcurveView.jsx]: Are you ready to pull these yet?

Comment (nikolas) [reply exoplanet-transit-simulator/src/LightcurveView.jsx]: oh - yeah. hold on.
